version: "3.9"
services:
  libras_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libras_service
    ports:
      - "8020:8020"
    environment:
      - PYTHONUNBUFFERED=1